# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Steven Fons
tagline:          'Personal website'
description:      'remote sensing scientist. sea ice researcher.'
url:              http://sfons.github.io


author:
  name:           'Steven Fons'
  url:            https://sfons.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sfons
